#!/bin/dash

url=https://www.verkeersbord.be/officieel/verkeersborden-overzicht/
dir=images
file="verkeersborden.html"
wgetc "$url" "$file"

[ -d $dir ] || mkdir $dir
cat "$file" | sed '/src="[^"]*.png"/!d;s/^\s*//;s/[^"]*"//;s/".*//;/lazy/d' | while read -r line
do
	name=$(echo "${line##*/}")
	wgetc "$line" "$dir/$name"
done

