<html>
<body>
<style>
	body{background-color: black;}
	body{color: grey;}
	*{font-size: 32px;}
	p{padding:0px; margin:8px;}
	a{color: #777; text-decoration: none;}
	a:visited{color: #333;}
	a:hover{text-decoration: underline;}
	table{margin:0px;}
	td{padding:5px; text-align: right;}
	.nohl:visited{color: #777}
	#footer{font-size: 40px;}
	input { background-color: #888; margin: 5px 0px; }
</style>
