<!DOCTYPE html>
<html>
<body>
<style>

	body{background-color: black;}
	body{color: grey;}
	p{padding:0px; margin:8px;}
	a{color: #777; text-decoration: none;}
	a:visited{color: #333;}
	a:hover{text-decoration: underline;}
	table{margin:0px;}
	td{padding:5px;}
	input { background-color: #888; margin: 5px 0px; }
	img { display:block; margin: 10px 0px; }
	sub { font-size: 0.6em; }

	*{font-size: 32px;}

	#footer{font-size: 40px;}
	#whitebox li{display: inline; list-style-type: none;}
	#whitebox table{border-collapse: collapse;}
	#whitebox td, #whitebox th {text-align: left; border: 1px dotted #888; margin: 0px; padding: 5px;}
	#whitebox tr *:last-of-type {display:none;}

	.nohl:visited{color: #777}

</style>
